### ISSUE TITLE
Darter Pro: Power button light is too bright.

### ISSUE THREAD

**Issue by bryanpaget** [system76/laptop-suggestions#87] opened 2019-12-26 16:55 UTC
### Why/User Benefit/User Problem

The power button light is too bright.

### Description of the feature

It should be able to adjust its brightness relative to the ambient lighting.

**Comment by Thulinma** [comment] 2019-12-26 21:23
Duplicate of #80 :+1:

**Comment by bryanpaget** [comment] 2019-12-26 21:46
Sorry.

**Closed as completed** 2023-01-20 21:22 UTC
